name: movie_app
version: 1.0.0+2
publish_to: none
description: A Movie App for Paras.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  auto_size_text: 3.0.0
  cached_network_image: ^3.2.2
  firebase_auth: ^4.1.3
  firebase_core: ^2.3.0
  google_fonts: 3.0.1
  google_sign_in: ^5.4.2
  page_transition: 2.0.4
  shared_preferences: 2.0.15
  font_awesome_flutter: 10.1.0
  sqflite: 2.2.0+2
  timeago: 3.2.2
  url_launcher: 6.1.5
  carousel_slider: ^4.1.1
  blur: ^3.1.0
  equatable: ^2.0.5
  either_dart: ^0.3.0
  shimmer: ^2.0.0
  get_storage: ^2.0.3
  flutter_staggered_grid_view: ^0.6.2
  number_pagination: ^0.0.3+2
  

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0

  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
  - assets/fonts/
  - assets/images/

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf

