name: movie_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  auto_size_text: 3.0.0
  cached_network_image: 3.2.1
  firebase_auth: ^4.1.3
  firebase_core: ^2.3.0
  google_fonts: 3.0.1
  google_sign_in: ^5.4.2
  page_transition: 2.0.4
  shared_preferences: 2.0.15
  font_awesome_flutter: 10.1.0
  sqflite: 2.2.0+2
  timeago: 3.2.2
  url_launcher: 6.1.5
  carousel_slider: ^4.1.1

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0

  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
  - assets/fonts/
  - assets/images/

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf

